// ── Types ─────────────────────────────────────────────────────

export type BrandCategory = 'Fashion' | 'Beauty' | 'Fitness' | 'Tech' | 'Food' | 'Travel'
export type BrandDifficulty = 'easy' | 'medium' | 'hard' | 'elite'
export type SortOption = 'match' | 'budget' | 'approval' | 'newest'
export type FilterCategory = BrandCategory | 'all'

export interface DiscoveryBrand {
  id: string
  name: string
  category: BrandCategory
  description: string
  tags: string[]
  budgetMin: number
  budgetMax: number
  compatibilityScore: number
  approvalRate: number
  difficulty: BrandDifficulty
  campaignCount: number
  addedAt: string
  requirements: string[]
  bestFor: string[]
}

// ── Config ────────────────────────────────────────────────────

export const DIFFICULTY_CONFIG: Record<BrandDifficulty, { label: string; color: string; bg: string }> = {
  easy:   { label: 'Easy',   color: '#22C55E', bg: 'rgba(34,197,94,0.12)'   },
  medium: { label: 'Medium', color: '#EAB308', bg: 'rgba(234,179,8,0.12)'   },
  hard:   { label: 'Hard',   color: '#F5A653', bg: 'rgba(245,166,83,0.12)'  },
  elite:  { label: 'Elite',  color: '#818CF8', bg: 'rgba(129,140,248,0.12)' },
}

export const CATEGORY_COLORS: Record<BrandCategory, string> = {
  Fashion:  '#F472B6',
  Beauty:   '#C084FC',
  Fitness:  '#22C55E',
  Tech:     '#38BDF8',
  Food:     '#FB923C',
  Travel:   '#34D399',
}

// ── Brand database (102 brands) ───────────────────────────────

const BRANDS: DiscoveryBrand[] = [
  // ── FASHION (18) ──────────────────────────────────────────
  {
    id: 'nike',
    name: 'Nike',
    category: 'Fashion',
    description: 'Global athletic brand rewarding high-energy, performance-driven creator content. Approve creators who show motion, sweat, and real effort over product showcase.',
    tags: ['athletic', 'performance', 'streetwear', 'running', 'basketball'],
    budgetMin: 15000, budgetMax: 80000,
    compatibilityScore: 82, approvalRate: 68,
    difficulty: 'medium', campaignCount: 14,
    addedAt: '2026-01-10T00:00:00Z',
    requirements: ['Open with movement — no static product shots', 'Creator must be physically active in video', 'No competitor sportswear visible', '60s max, 30s preferred for Reels'],
    bestFor: ['Athletic performance creators', 'Fitness & sport accounts', 'Street culture influencers'],
  },
  {
    id: 'adidas',
    name: 'Adidas',
    category: 'Fashion',
    description: 'Sport and lifestyle brand that blends performance with culture. Values authentic creator stories over polished ads — street and studio both welcome.',
    tags: ['sport', 'lifestyle', 'street', 'culture', 'originals'],
    budgetMin: 12000, budgetMax: 70000,
    compatibilityScore: 78, approvalRate: 65,
    difficulty: 'medium', campaignCount: 11,
    addedAt: '2026-01-22T00:00:00Z',
    requirements: ['Creator voice required — no voiceover', 'Show product in authentic setting', 'Diversity of movement encouraged', 'No scripted greetings'],
    bestFor: ['Street fashion creators', 'Sport lifestyle influencers', 'Culture & music accounts'],
  },
  {
    id: 'levis',
    name: "Levi's",
    category: 'Fashion',
    description: 'Iconic denim brand that consistently backs creator-authentic content. High approval rate for lifestyle storytelling; comfortable with imperfect aesthetics.',
    tags: ['denim', 'casual', 'americana', 'lifestyle', 'heritage'],
    budgetMin: 8000, budgetMax: 45000,
    compatibilityScore: 85, approvalRate: 75,
    difficulty: 'easy', campaignCount: 9,
    addedAt: '2026-02-05T00:00:00Z',
    requirements: ["Style the product your way — brand doesn't dictate looks", 'Show product in everyday life', 'Authenticity over production quality'],
    bestFor: ['Lifestyle creators', 'Casual fashion accounts', 'Americana & heritage niches'],
  },
  {
    id: 'zara',
    name: 'Zara',
    category: 'Fashion',
    description: 'Fast-fashion giant with high visual standards. Approval is demanding — requires editorial-quality aesthetics and specific styling language.',
    tags: ['fast-fashion', 'editorial', 'contemporary', 'trend', 'minimalist'],
    budgetMin: 5000, budgetMax: 25000,
    compatibilityScore: 62, approvalRate: 40,
    difficulty: 'hard', campaignCount: 5,
    addedAt: '2026-03-14T00:00:00Z',
    requirements: ['Editorial visual quality required', 'Minimal voiceover — let styling speak', 'Neutral backgrounds preferred', 'Product must be hero of the frame'],
    bestFor: ['Editorial fashion creators', 'High-aesthetic lifestyle accounts', 'European fashion influencers'],
  },
  {
    id: 'hm',
    name: 'H&M',
    category: 'Fashion',
    description: 'Affordable fashion brand with a broad creator brief. More accessible than luxury peers, values diversity and inclusive content.',
    tags: ['affordable', 'fast-fashion', 'inclusive', 'basics', 'seasonal'],
    budgetMin: 4000, budgetMax: 20000,
    compatibilityScore: 71, approvalRate: 62,
    difficulty: 'medium', campaignCount: 18,
    addedAt: '2025-12-08T00:00:00Z',
    requirements: ['Inclusive representation encouraged', 'Show multiple outfit options where possible', 'Trend-forward but accessible styling'],
    bestFor: ['Everyday lifestyle creators', 'Fashion on a budget accounts', 'Inclusive fashion voices'],
  },
  {
    id: 'mango',
    name: 'Mango',
    category: 'Fashion',
    description: 'Contemporary European fashion brand with a relaxed approval process for creators who match their minimalist, chic aesthetic.',
    tags: ['contemporary', 'european', 'minimalist', 'chic', 'womenswear'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 76, approvalRate: 70,
    difficulty: 'easy', campaignCount: 8,
    addedAt: '2026-02-18T00:00:00Z',
    requirements: ['Mediterranean / European styling angle preferred', 'Minimal heavy edits', 'Natural light settings score higher'],
    bestFor: ['European lifestyle creators', 'Minimalist fashion accounts', 'Travel-adjacent fashion content'],
  },
  {
    id: 'tommy-hilfiger',
    name: 'Tommy Hilfiger',
    category: 'Fashion',
    description: 'Premium American casual brand balancing heritage with modern creator culture. Values preppy-meets-street aesthetic in content.',
    tags: ['premium', 'preppy', 'american', 'casual', 'heritage'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 74, approvalRate: 55,
    difficulty: 'medium', campaignCount: 7,
    addedAt: '2026-01-30T00:00:00Z',
    requirements: ['Brand heritage angle appreciated', 'Show product in aspirational but accessible setting', 'Avoid overly casual or low-energy presentation'],
    bestFor: ['Preppy & campus lifestyle creators', 'Premium casual fashion accounts', 'Americana culture influencers'],
  },
  {
    id: 'calvin-klein',
    name: 'Calvin Klein',
    category: 'Fashion',
    description: 'Luxury-adjacent minimalist brand with strict aesthetic standards. Rejection rate is high — they value bold, confident, stripped-back visuals.',
    tags: ['minimalist', 'luxury', 'underwear', 'denim', 'bold'],
    budgetMin: 10000, budgetMax: 55000,
    compatibilityScore: 68, approvalRate: 45,
    difficulty: 'hard', campaignCount: 6,
    addedAt: '2026-04-02T00:00:00Z',
    requirements: ['Minimal styling — product is the statement', 'Bold, confident posing and energy', 'Clean backgrounds only', 'No comedic or casual tone'],
    bestFor: ['Bold editorial creators', 'Body-positive fashion accounts', 'High-fashion adjacent influencers'],
  },
  {
    id: 'gucci',
    name: 'Gucci',
    category: 'Fashion',
    description: 'Luxury house with elite approval standards. Extremely selective creator partnerships — but budgets are the highest in category.',
    tags: ['luxury', 'high-fashion', 'italian', 'iconic', 'designer'],
    budgetMin: 25000, budgetMax: 120000,
    compatibilityScore: 61, approvalRate: 28,
    difficulty: 'elite', campaignCount: 3,
    addedAt: '2026-05-01T00:00:00Z',
    requirements: ['Only creators with documented luxury aesthetic', 'High-production quality mandatory', 'No UGC-style content', 'Brand must approve all creative before filming'],
    bestFor: ['Luxury lifestyle creators', 'High-fashion editorial accounts', 'Celebrity-adjacent influencers'],
  },
  {
    id: 'puma',
    name: 'Puma',
    category: 'Fashion',
    description: 'Sport-fashion brand that bridges athletics and streetwear. More flexible approval process than Nike or Adidas — values culture and movement equally.',
    tags: ['sport', 'streetwear', 'culture', 'running', 'motorsport'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 80, approvalRate: 72,
    difficulty: 'easy', campaignCount: 10,
    addedAt: '2026-03-20T00:00:00Z',
    requirements: ['Show product in motion or street setting', 'Culture tie-in (sport, music, art) preferred', 'Creator energy must match brand boldness'],
    bestFor: ['Street culture creators', 'Sport lifestyle accounts', 'Music and fashion crossover influencers'],
  },
  {
    id: 'new-balance',
    name: 'New Balance',
    category: 'Fashion',
    description: "Heritage running brand that's had a major cultural resurgence. Highly creator-friendly and values authenticity and genuine product affinity.",
    tags: ['running', 'heritage', 'dad-shoe', 'street', 'cultural-moment'],
    budgetMin: 8000, budgetMax: 38000,
    compatibilityScore: 84, approvalRate: 76,
    difficulty: 'easy', campaignCount: 12,
    addedAt: '2026-02-28T00:00:00Z',
    requirements: ['Genuine product fan vibe preferred', 'Lifestyle or street setting over gym', 'Subtle product integration scores higher than forced showcase'],
    bestFor: ['Street style creators', 'Cultural commentary accounts', 'Lifestyle influencers with cult followings'],
  },
  {
    id: 'vans',
    name: 'Vans',
    category: 'Fashion',
    description: 'Counter-culture skate brand with the most relaxed brief in footwear. Values raw authenticity — even messy aesthetics get approved.',
    tags: ['skate', 'street', 'music', 'art', 'youth-culture'],
    budgetMin: 6000, budgetMax: 28000,
    compatibilityScore: 86, approvalRate: 78,
    difficulty: 'easy', campaignCount: 15,
    addedAt: '2025-12-20T00:00:00Z',
    requirements: ['Raw, unfiltered aesthetic wins', 'Skate, music, or art tie-in preferred', 'No high-production polish expected', 'Creator subculture must be genuine'],
    bestFor: ['Skate & surf creators', 'Music and art crossover accounts', 'Youth subculture influencers'],
  },
  {
    id: 'converse',
    name: 'Converse',
    category: 'Fashion',
    description: 'Iconic American sneaker brand that backs creative self-expression. Extremely accessible for creators — individuality is the brief.',
    tags: ['classic', 'sneaker', 'art', 'self-expression', 'creative'],
    budgetMin: 5000, budgetMax: 25000,
    compatibilityScore: 83, approvalRate: 74,
    difficulty: 'easy', campaignCount: 13,
    addedAt: '2026-01-15T00:00:00Z',
    requirements: ['Express your own identity with the product', 'Cross-genre content welcomed', 'No formula — individuality is the only requirement'],
    bestFor: ['Creative expression accounts', 'Art & music crossover creators', 'Youth identity influencers'],
  },
  {
    id: 'reebok',
    name: 'Reebok',
    category: 'Fashion',
    description: 'Legacy athletic brand repositioning in fitness and street culture. Values performance storytelling with authentic creator perspectives.',
    tags: ['athletic', 'fitness', 'street', 'crossfit', 'heritage'],
    budgetMin: 7000, budgetMax: 32000,
    compatibilityScore: 77, approvalRate: 68,
    difficulty: 'medium', campaignCount: 8,
    addedAt: '2026-03-05T00:00:00Z',
    requirements: ['Performance or fitness context required', 'Show product in real training environment', 'Energy and movement must be authentic'],
    bestFor: ['CrossFit and functional fitness creators', 'Street fashion accounts with sport edge', 'Retro athletic aesthetic influencers'],
  },
  {
    id: 'superdry',
    name: 'Superdry',
    category: 'Fashion',
    description: 'British casual brand with easy approval process for lifestyle content. Values adventure-adjacent and outdoor casual aesthetics.',
    tags: ['british', 'casual', 'outdoor', 'adventure', 'lifestyle'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 79, approvalRate: 70,
    difficulty: 'easy', campaignCount: 9,
    addedAt: '2026-04-18T00:00:00Z',
    requirements: ['Outdoor or adventure setting preferred', 'Seasonal relevance important', 'Lifestyle integration over product focus'],
    bestFor: ['Outdoor lifestyle creators', 'Adventure travel accounts', 'British & European lifestyle influencers'],
  },
  {
    id: 'jack-jones',
    name: 'Jack & Jones',
    category: 'Fashion',
    description: 'Scandinavian menswear brand with an accessible creator program. Values everyday urban male lifestyle content.',
    tags: ['menswear', 'scandinavian', 'urban', 'casual', 'denim'],
    budgetMin: 4000, budgetMax: 18000,
    compatibilityScore: 75, approvalRate: 66,
    difficulty: 'medium', campaignCount: 10,
    addedAt: '2026-02-12T00:00:00Z',
    requirements: ['Male creator preferred but not required', 'Urban everyday styling', 'Real-life settings over studio'],
    bestFor: ['Menswear creators', 'Urban lifestyle accounts', 'Everyday fashion influencers'],
  },
  {
    id: 'only',
    name: 'ONLY',
    category: 'Fashion',
    description: 'Contemporary womenswear brand with high creator flexibility. Values trend-forward content with accessible, authentic energy.',
    tags: ['womenswear', 'trend', 'accessible', 'contemporary', 'seasonal'],
    budgetMin: 4000, budgetMax: 16000,
    compatibilityScore: 81, approvalRate: 74,
    difficulty: 'easy', campaignCount: 12,
    addedAt: '2026-03-28T00:00:00Z',
    requirements: ['Trend-forward styling encouraged', 'Creator personality must come through', 'Seasonal lookbook format preferred'],
    bestFor: ['Female fashion creators', 'Trend-forward lifestyle accounts', 'OOTD and styling influencers'],
  },
  {
    id: 'ralph-lauren',
    name: 'Ralph Lauren',
    category: 'Fashion',
    description: 'Aspirational American lifestyle brand with selective approval. Values timeless, polished aesthetics and premium lifestyle contexts.',
    tags: ['luxury', 'preppy', 'american', 'polo', 'heritage'],
    budgetMin: 12000, budgetMax: 60000,
    compatibilityScore: 72, approvalRate: 48,
    difficulty: 'hard', campaignCount: 5,
    addedAt: '2026-04-25T00:00:00Z',
    requirements: ['Aspirational lifestyle setting required', 'Polished production — no handheld wobble', 'Brand storytelling over product showcase', 'No humor or casual energy'],
    bestFor: ['Luxury lifestyle creators', 'Equestrian & country club adjacent accounts', 'Aspirational travel influencers'],
  },

  // ── BEAUTY (17) ───────────────────────────────────────────
  {
    id: 'maybelline',
    name: 'Maybelline',
    category: 'Beauty',
    description: 'Mass-market cosmetics brand with one of the highest creator approval rates in beauty. Values real-face makeup application and accessible tutorials.',
    tags: ['cosmetics', 'makeup', 'drugstore', 'tutorial', 'affordable'],
    budgetMin: 6000, budgetMax: 30000,
    compatibilityScore: 86, approvalRate: 78,
    difficulty: 'easy', campaignCount: 22,
    addedAt: '2025-12-15T00:00:00Z',
    requirements: ['Show product application on real skin — no heavy filtering', 'Tutorial or GRWM format preferred', 'Before/after moment required for coverage products'],
    bestFor: ['Makeup tutorial creators', 'Everyday beauty accounts', 'Drugstore beauty influencers'],
  },
  {
    id: 'loreal',
    name: "L'Oréal Paris",
    category: 'Beauty',
    description: 'Global beauty leader with broad campaign scope. Approves diverse skin tones and creator styles — premium feel without luxury gatekeeping.',
    tags: ['cosmetics', 'skincare', 'hair', 'premium-mass', 'science-backed'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 82, approvalRate: 70,
    difficulty: 'medium', campaignCount: 19,
    addedAt: '2026-01-08T00:00:00Z',
    requirements: ['Show efficacy claim in action', 'Creator must demonstrate product use on themselves', 'Science or ingredient mention preferred for skincare line'],
    bestFor: ['Beauty educators', 'Multi-category beauty creators', 'Science-backed skincare accounts'],
  },
  {
    id: 'nyx',
    name: 'NYX Professional Makeup',
    category: 'Beauty',
    description: 'Pro-level cosmetics brand built by creators. Extremely high approval rate — they partner with bold, creative makeup artists at all follower levels.',
    tags: ['professional', 'bold', 'colorful', 'artistry', 'affordable'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 88, approvalRate: 82,
    difficulty: 'easy', campaignCount: 25,
    addedAt: '2026-02-03T00:00:00Z',
    requirements: ['Creative bold makeup looks encouraged', 'Any skin tone and style welcomed', 'Artistic transformation content performs best'],
    bestFor: ['Makeup artists', 'Bold beauty creators', 'Color and artistry accounts'],
  },
  {
    id: 'mac',
    name: 'MAC Cosmetics',
    category: 'Beauty',
    description: 'Professional heritage cosmetics brand that values artistry and technique. Medium difficulty — strong creative vision opens doors.',
    tags: ['professional', 'artistry', 'editorial', 'inclusive', 'backstage'],
    budgetMin: 8000, budgetMax: 38000,
    compatibilityScore: 79, approvalRate: 65,
    difficulty: 'medium', campaignCount: 14,
    addedAt: '2026-01-28T00:00:00Z',
    requirements: ['Artistry and technique must be demonstrable', 'Pro or semi-pro makeup skills required', 'Backstage or editorial angle preferred'],
    bestFor: ['Professional makeup artists', 'Editorial beauty creators', 'High-skill technique accounts'],
  },
  {
    id: 'charlotte-tilbury',
    name: 'Charlotte Tilbury',
    category: 'Beauty',
    description: 'Luxury British beauty brand with a glam-focused brief. High approval standards — they want polished, glamorous, red-carpet adjacent content.',
    tags: ['luxury', 'glamour', 'british', 'skincare', 'red-carpet'],
    budgetMin: 12000, budgetMax: 55000,
    compatibilityScore: 74, approvalRate: 52,
    difficulty: 'hard', campaignCount: 8,
    addedAt: '2026-04-10T00:00:00Z',
    requirements: ['Glamour and polish required', 'Skin must look radiant — no heavy filter masking', 'Product must be shown as a hero item', 'Luxury setting preferred'],
    bestFor: ['Luxury beauty creators', 'Glamour and red-carpet accounts', 'High-production beauty influencers'],
  },
  {
    id: 'rare-beauty',
    name: 'Rare Beauty',
    category: 'Beauty',
    description: "Selena Gomez's inclusive beauty brand with a mental health mission. Values authentic, unfiltered beauty content — real skin, real people.",
    tags: ['inclusive', 'mental-health', 'dewy', 'authentic', 'feel-good'],
    budgetMin: 7000, budgetMax: 35000,
    compatibilityScore: 87, approvalRate: 79,
    difficulty: 'easy', campaignCount: 17,
    addedAt: '2026-02-20T00:00:00Z',
    requirements: ['Authenticity first — real skin and real moments', 'Mental health and self-acceptance messaging welcomed', 'No beauty perfection tropes'],
    bestFor: ['Inclusive beauty creators', 'Mental wellness and beauty crossover accounts', 'Authentic lifestyle influencers'],
  },
  {
    id: 'fenty-beauty',
    name: 'Fenty Beauty',
    category: 'Beauty',
    description: "Rihanna's boundary-breaking beauty brand. Actively seeks diverse skin tones and creator backgrounds — difficulty is medium despite premium positioning.",
    tags: ['inclusive', 'diverse', 'foundation', 'bold', 'boundary-breaking'],
    budgetMin: 9000, budgetMax: 45000,
    compatibilityScore: 84, approvalRate: 72,
    difficulty: 'medium', campaignCount: 16,
    addedAt: '2026-01-18T00:00:00Z',
    requirements: ['Shade range representation matters — show your actual shade', 'Bold or unexpected looks encouraged', 'Diverse creator backgrounds actively sought'],
    bestFor: ['Diverse skin tone beauty creators', 'Bold makeup accounts', 'Inclusive beauty advocates'],
  },
  {
    id: 'nars',
    name: 'NARS',
    category: 'Beauty',
    description: 'Prestige cosmetics brand with an unapologetically sensual, editorial aesthetic. High difficulty — they have a very specific visual language.',
    tags: ['prestige', 'editorial', 'sensual', 'bold', 'french'],
    budgetMin: 10000, budgetMax: 48000,
    compatibilityScore: 75, approvalRate: 55,
    difficulty: 'hard', campaignCount: 7,
    addedAt: '2026-03-22T00:00:00Z',
    requirements: ['NARS aesthetic: bold, confident, unapologetic', 'Orgasm palette and hero products featured prominently', 'Editorial quality imagery'],
    bestFor: ['Editorial makeup artists', 'Bold confidence beauty accounts', 'French beauty aesthetic creators'],
  },
  {
    id: 'urban-decay',
    name: 'Urban Decay',
    category: 'Beauty',
    description: 'Counter-culture cosmetics brand that rewards edgy, unapologetic creator content. Higher approval rate for creators with alternative or bold aesthetics.',
    tags: ['edgy', 'alternative', 'bold', 'colorful', 'counter-culture'],
    budgetMin: 7000, budgetMax: 30000,
    compatibilityScore: 80, approvalRate: 68,
    difficulty: 'medium', campaignCount: 11,
    addedAt: '2026-02-08T00:00:00Z',
    requirements: ['Bold, rule-breaking looks encouraged', 'Alternative aesthetics welcomed', 'No safe, predictable looks — push boundaries'],
    bestFor: ['Alternative beauty creators', 'Edgy makeup accounts', 'Counter-culture influencers'],
  },
  {
    id: 'too-faced',
    name: 'Too Faced',
    category: 'Beauty',
    description: 'Fun, feminine cosmetics brand with a playful brief. Easy entry point for lifestyle-adjacent beauty creators.',
    tags: ['fun', 'feminine', 'pink', 'mascara', 'glam'],
    budgetMin: 6000, budgetMax: 28000,
    compatibilityScore: 82, approvalRate: 73,
    difficulty: 'easy', campaignCount: 14,
    addedAt: '2026-04-05T00:00:00Z',
    requirements: ['Fun, upbeat energy — no serious or clinical tone', 'Show product in playful context', 'Glam or feminine aesthetic preferred'],
    bestFor: ['Feminine lifestyle creators', 'Fun beauty accounts', 'Glam makeup influencers'],
  },
  {
    id: 'the-ordinary',
    name: 'The Ordinary',
    category: 'Beauty',
    description: 'Science-first skincare brand with the highest approval rate in beauty. Rewards educational, ingredient-focused content — no need for aesthetic polish.',
    tags: ['skincare', 'science', 'ingredients', 'affordable', 'no-nonsense'],
    budgetMin: 4000, budgetMax: 18000,
    compatibilityScore: 89, approvalRate: 84,
    difficulty: 'easy', campaignCount: 28,
    addedAt: '2025-12-01T00:00:00Z',
    requirements: ['Ingredient education is the content format', 'Honest, no-hype language required', 'Show real skin results — no beauty filters'],
    bestFor: ['Skincare science educators', 'No-nonsense beauty accounts', 'Ingredient-focused creators'],
  },
  {
    id: 'cerave',
    name: 'CeraVe',
    category: 'Beauty',
    description: 'Dermatologist-backed skincare brand with a massive creator program. Easy approval for genuine skincare advocates — budget is modest but volume is high.',
    tags: ['skincare', 'dermatology', 'drugstore', 'sensitive-skin', 'barrier'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 85, approvalRate: 80,
    difficulty: 'easy', campaignCount: 32,
    addedAt: '2025-12-28T00:00:00Z',
    requirements: ['Dermatologist recommendation angle preferred', 'Show routine integration naturally', 'Sensitive skin and barrier-care messaging valued'],
    bestFor: ['Skincare routine creators', 'Dermatology-adjacent accounts', 'Sensitive skin advocates'],
  },
  {
    id: 'la-roche-posay',
    name: 'La Roche-Posay',
    category: 'Beauty',
    description: 'French pharmacy skincare with strong creator trust signals. Values clinical credibility and genuine skin concern backstories.',
    tags: ['french-pharmacy', 'clinical', 'sensitive-skin', 'spf', 'dermatology'],
    budgetMin: 6000, budgetMax: 25000,
    compatibilityScore: 83, approvalRate: 76,
    difficulty: 'easy', campaignCount: 20,
    addedAt: '2026-01-05T00:00:00Z',
    requirements: ['Clinical or dermatology angle required', 'Creator must have genuine skin concern to share', 'SPF and sun protection messaging for summer campaigns'],
    bestFor: ['Skincare educators', 'Eczema and sensitive skin accounts', 'French beauty aesthetic creators'],
  },
  {
    id: 'kiehls',
    name: "Kiehl's",
    category: 'Beauty',
    description: 'Premium heritage skincare brand with a pharmacy aesthetic. Medium difficulty — values understated luxury and ingredient storytelling.',
    tags: ['premium', 'heritage', 'skincare', 'pharmacy', 'natural'],
    budgetMin: 8000, budgetMax: 35000,
    compatibilityScore: 77, approvalRate: 60,
    difficulty: 'medium', campaignCount: 10,
    addedAt: '2026-03-10T00:00:00Z',
    requirements: ['Heritage and ingredient storytelling valued', 'Understated luxury aesthetic', 'Show ritual and routine — not one-off application'],
    bestFor: ['Premium skincare creators', 'Heritage brand enthusiasts', 'Skincare ritual accounts'],
  },
  {
    id: 'drunk-elephant',
    name: 'Drunk Elephant',
    category: 'Beauty',
    description: 'Clean skincare brand with a passionate community. Creator approval is medium — they value clean ingredient advocacy and genuine brand alignment.',
    tags: ['clean-beauty', 'skincare', 'colorful', 'community', 'no-silicone'],
    budgetMin: 9000, budgetMax: 40000,
    compatibilityScore: 79, approvalRate: 63,
    difficulty: 'medium', campaignCount: 12,
    addedAt: '2026-02-25T00:00:00Z',
    requirements: ['Clean beauty advocacy must feel genuine', 'Show ingredient philosophy understanding', 'Community-first tone over sales-first'],
    bestFor: ['Clean beauty creators', 'Skincare ingredient advocates', 'Wellness-beauty crossover accounts'],
  },
  {
    id: 'tatcha',
    name: 'Tatcha',
    category: 'Beauty',
    description: 'Luxury Japanese-inspired skincare with strict aesthetic requirements. High difficulty — values reverence for Japanese beauty rituals and premium presentation.',
    tags: ['japanese', 'luxury', 'ritual', 'skincare', 'geisha-inspired'],
    budgetMin: 12000, budgetMax: 55000,
    compatibilityScore: 72, approvalRate: 50,
    difficulty: 'hard', campaignCount: 6,
    addedAt: '2026-04-28T00:00:00Z',
    requirements: ['Japanese beauty ritual appreciation required', 'Premium, unhurried presentation style', 'No casual or comedic tone', 'Tranquil aesthetic settings'],
    bestFor: ['Luxury skincare creators', 'Japanese beauty enthusiasts', 'Slow-beauty ritual accounts'],
  },
  {
    id: 'innisfree',
    name: 'Innisfree',
    category: 'Beauty',
    description: 'Korean beauty brand from Jeju Island. Easy approval for K-beauty creators — values natural ingredients and clean, fresh aesthetics.',
    tags: ['k-beauty', 'natural', 'jeju', 'clean', 'skincare'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 81, approvalRate: 75,
    difficulty: 'easy', campaignCount: 16,
    addedAt: '2026-03-02T00:00:00Z',
    requirements: ['K-beauty or natural ingredient angle preferred', 'Fresh, clean aesthetic — nature settings welcome', 'Honest ingredient and efficacy discussion valued'],
    bestFor: ['K-beauty creators', 'Natural beauty accounts', 'Clean skincare advocates'],
  },

  // ── FITNESS (17) ──────────────────────────────────────────
  {
    id: 'gymshark',
    name: 'Gymshark',
    category: 'Fitness',
    description: "Creator-born fitness brand with the industry's highest approval rate. Built its brand on creator content — genuine gym culture is the only requirement.",
    tags: ['gym', 'activewear', 'lifting', 'bodybuilding', 'community'],
    budgetMin: 8000, budgetMax: 45000,
    compatibilityScore: 91, approvalRate: 82,
    difficulty: 'easy', campaignCount: 35,
    addedAt: '2025-12-05T00:00:00Z',
    requirements: ['Real gym environment required', 'Show your actual training — not staged lifts', 'Community and transformation stories perform best'],
    bestFor: ['Gym and strength training creators', 'Fitness transformation accounts', 'Bodybuilding and physique influencers'],
  },
  {
    id: 'lululemon',
    name: 'Lululemon',
    category: 'Fitness',
    description: 'Premium activewear brand with strong aesthetic standards. Medium difficulty — values mindfulness, performance, and aspirational lifestyle content.',
    tags: ['yoga', 'running', 'mindfulness', 'premium', 'activewear'],
    budgetMin: 12000, budgetMax: 60000,
    compatibilityScore: 85, approvalRate: 70,
    difficulty: 'medium', campaignCount: 18,
    addedAt: '2026-01-12T00:00:00Z',
    requirements: ['Mindfulness or performance lifestyle context required', 'Aesthetic quality matters more than production cost', 'Show product in genuine workout or wellness setting'],
    bestFor: ['Yoga and wellness creators', 'Premium fitness lifestyle accounts', 'Running and outdoor fitness influencers'],
  },
  {
    id: 'under-armour',
    name: 'Under Armour',
    category: 'Fitness',
    description: 'Performance athletic brand focused on training. Values creator content showing real effort and performance metrics over aesthetics.',
    tags: ['performance', 'training', 'sport', 'compression', 'athletic'],
    budgetMin: 10000, budgetMax: 50000,
    compatibilityScore: 80, approvalRate: 65,
    difficulty: 'medium', campaignCount: 14,
    addedAt: '2026-02-14T00:00:00Z',
    requirements: ['Performance context required — show effort and sweat', 'Training metrics or goals preferred', 'Brand is performance-first, not lifestyle-first'],
    bestFor: ['High-performance training creators', 'Athletic sport accounts', 'Military and tactical fitness influencers'],
  },
  {
    id: 'myprotein',
    name: 'Myprotein',
    category: 'Fitness',
    description: 'Leading European sports nutrition brand with a massive creator program. Easiest entry point in supplements — volume over prestige.',
    tags: ['supplements', 'protein', 'nutrition', 'gym', 'science'],
    budgetMin: 5000, budgetMax: 28000,
    compatibilityScore: 88, approvalRate: 80,
    difficulty: 'easy', campaignCount: 40,
    addedAt: '2025-12-10T00:00:00Z',
    requirements: ['Show product as part of real training routine', 'Honest flavor and texture review welcomed', 'Stack with genuine fitness content — not just product review'],
    bestFor: ['Gym and nutrition creators', 'Fitness review accounts', 'Sports performance influencers'],
  },
  {
    id: 'optimum-nutrition',
    name: 'Optimum Nutrition',
    category: 'Fitness',
    description: 'Gold Standard supplements brand. Values proven performance — favors creators who can discuss nutrition science naturally.',
    tags: ['protein', 'nutrition', 'gold-standard', 'supplements', 'science'],
    budgetMin: 6000, budgetMax: 30000,
    compatibilityScore: 84, approvalRate: 76,
    difficulty: 'easy', campaignCount: 22,
    addedAt: '2025-12-22T00:00:00Z',
    requirements: ['Nutrition or supplement knowledge preferred', 'Show product in real training context', 'Performance outcomes and honest reviews favored'],
    bestFor: ['Sports nutrition creators', 'Gym and bodybuilding accounts', 'Performance athlete influencers'],
  },
  {
    id: 'bsn',
    name: 'BSN',
    category: 'Fitness',
    description: 'Syntha-6 and NO-Xplode maker with a focused creator brief. Easy approval for gym-authentic creators with any following size.',
    tags: ['pre-workout', 'protein', 'supplements', 'gym', 'performance'],
    budgetMin: 5000, budgetMax: 25000,
    compatibilityScore: 80, approvalRate: 72,
    difficulty: 'easy', campaignCount: 18,
    addedAt: '2026-01-25T00:00:00Z',
    requirements: ['Pre-workout or intra-workout context for those products', 'Real training environment', 'Honest taste and mixability review appreciated'],
    bestFor: ['Gym creators', 'Pre-workout review accounts', 'Performance supplement influencers'],
  },
  {
    id: 'gnc',
    name: 'GNC',
    category: 'Fitness',
    description: 'US health and wellness retail brand with a broad creator program. Medium difficulty — values health positioning over pure gym content.',
    tags: ['health', 'wellness', 'vitamins', 'supplements', 'retail'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 75, approvalRate: 62,
    difficulty: 'medium', campaignCount: 16,
    addedAt: '2026-03-08T00:00:00Z',
    requirements: ['Health and wellness lifestyle angle required', 'Broad health positioning — not gym-only', 'Authentic daily routine integration'],
    bestFor: ['General wellness creators', 'Health lifestyle accounts', 'Supplement review influencers'],
  },
  {
    id: 'peloton',
    name: 'Peloton',
    category: 'Fitness',
    description: 'Connected fitness platform with high investment per creator. Medium difficulty — values community-driven fitness transformation stories.',
    tags: ['connected-fitness', 'cycling', 'community', 'transformation', 'home-gym'],
    budgetMin: 12000, budgetMax: 55000,
    compatibilityScore: 76, approvalRate: 58,
    difficulty: 'medium', campaignCount: 9,
    addedAt: '2026-02-22T00:00:00Z',
    requirements: ['Must own or have access to Peloton equipment', 'Community angle over product spec', 'Transformation or consistency story valued'],
    bestFor: ['Home fitness creators', 'Indoor cycling accounts', 'Fitness community influencers'],
  },
  {
    id: 'whoop',
    name: 'WHOOP',
    category: 'Fitness',
    description: 'Performance monitoring wearable for serious athletes. Medium difficulty — needs creators who track genuine performance metrics.',
    tags: ['wearable', 'recovery', 'hrv', 'performance', 'data-driven'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 79, approvalRate: 63,
    difficulty: 'medium', campaignCount: 11,
    addedAt: '2026-04-15T00:00:00Z',
    requirements: ['Creator must use product during real training', 'Data-driven performance content preferred', 'Recovery and sleep angle equally valuable as training'],
    bestFor: ['Data-driven fitness creators', 'Elite athlete accounts', 'Recovery and optimization influencers'],
  },
  {
    id: 'garmin',
    name: 'Garmin',
    category: 'Fitness',
    description: 'GPS and fitness wearable brand. Values adventure and endurance sport contexts — running, cycling, hiking.',
    tags: ['gps', 'running', 'cycling', 'outdoor', 'wearable'],
    budgetMin: 10000, budgetMax: 45000,
    compatibilityScore: 77, approvalRate: 60,
    difficulty: 'medium', campaignCount: 13,
    addedAt: '2026-03-16T00:00:00Z',
    requirements: ['Outdoor or endurance sport context required', 'Show GPS data in actual use', 'Adventure and multi-sport content favored'],
    bestFor: ['Running and cycling creators', 'Adventure sport accounts', 'Outdoor endurance influencers'],
  },
  {
    id: 'trx',
    name: 'TRX Training',
    category: 'Fitness',
    description: 'Suspension training brand with easy creator approval. Values creative workout demonstrations and functional fitness content.',
    tags: ['suspension', 'functional', 'bodyweight', 'portable', 'training'],
    budgetMin: 5000, budgetMax: 25000,
    compatibilityScore: 83, approvalRate: 76,
    difficulty: 'easy', campaignCount: 14,
    addedAt: '2026-01-20T00:00:00Z',
    requirements: ['Show product in use with real exercises', 'Creative workout demos perform best', 'Home or outdoor training environments welcome'],
    bestFor: ['Functional fitness creators', 'Home gym accounts', 'Bodyweight training influencers'],
  },
  {
    id: 'onnit',
    name: 'Onnit',
    category: 'Fitness',
    description: 'Total human optimization brand. Values mindset and performance content — creator alignment with the "be better" philosophy is key.',
    tags: ['total-human', 'performance', 'nootropics', 'kettlebell', 'mindset'],
    budgetMin: 6000, budgetMax: 28000,
    compatibilityScore: 82, approvalRate: 74,
    difficulty: 'easy', campaignCount: 12,
    addedAt: '2026-02-10T00:00:00Z',
    requirements: ['Mindset and performance philosophy alignment required', 'Show functional training over aesthetic-only fitness', 'Joe Rogan-adjacent audiences respond well'],
    bestFor: ['Performance mindset creators', 'Functional fitness accounts', 'MMA and combat sport influencers'],
  },
  {
    id: 'hyperice',
    name: 'Hyperice',
    category: 'Fitness',
    description: 'Recovery technology brand. Values genuine athlete recovery content — ice baths, percussive therapy, and post-workout rituals.',
    tags: ['recovery', 'ice-bath', 'percussion', 'athlete', 'technology'],
    budgetMin: 7000, budgetMax: 35000,
    compatibilityScore: 80, approvalRate: 70,
    difficulty: 'medium', campaignCount: 10,
    addedAt: '2026-03-25T00:00:00Z',
    requirements: ['Recovery ritual in real training context', 'Athlete or serious fitness lifestyle required', 'Show recovery as performance investment'],
    bestFor: ['Athlete and elite fitness creators', 'Recovery and biohacking accounts', 'Sports performance influencers'],
  },
  {
    id: 'theragun',
    name: 'Theragun',
    category: 'Fitness',
    description: 'Percussive therapy brand. Medium difficulty — values genuine recovery need stories over product demo content.',
    tags: ['percussive', 'recovery', 'muscle', 'therapy', 'tech'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 78, approvalRate: 65,
    difficulty: 'medium', campaignCount: 9,
    addedAt: '2026-04-20T00:00:00Z',
    requirements: ['Show genuine muscle recovery need — not just product demo', 'Before/after soreness or injury recovery story valued', 'Professional athlete endorsement angle preferred if possible'],
    bestFor: ['Athlete recovery creators', 'Physical therapy adjacent accounts', 'Elite sport and fitness influencers'],
  },
  {
    id: 'science-in-sport',
    name: 'Science in Sport',
    category: 'Fitness',
    description: 'Elite sports nutrition brand. Easy approval for endurance sport creators — gels, hydration, and performance nutrition.',
    tags: ['endurance', 'nutrition', 'cycling', 'running', 'gels'],
    budgetMin: 4000, budgetMax: 20000,
    compatibilityScore: 85, approvalRate: 78,
    difficulty: 'easy', campaignCount: 20,
    addedAt: '2026-01-03T00:00:00Z',
    requirements: ['Endurance sport context required (running, cycling, triathlon)', 'Show product in race or long training session', 'Nutrition science discussion valued'],
    bestFor: ['Endurance sport creators', 'Marathon and cycling accounts', 'Triathlon and ultra-endurance influencers'],
  },
  {
    id: 'fitbit',
    name: 'Fitbit',
    category: 'Fitness',
    description: 'Consumer fitness tracking brand. Values everyday health improvement stories — not elite athlete content.',
    tags: ['wearable', 'steps', 'health', 'sleep', 'everyday'],
    budgetMin: 8000, budgetMax: 35000,
    compatibilityScore: 74, approvalRate: 58,
    difficulty: 'medium', campaignCount: 10,
    addedAt: '2026-02-06T00:00:00Z',
    requirements: ['Everyday health improvement story preferred', 'Show product in daily life — not just workouts', 'Sleep tracking and wellness content equally valued'],
    bestFor: ['Everyday wellness creators', 'Health habit accounts', 'General fitness improvement influencers'],
  },
  {
    id: 'bowflex',
    name: 'Bowflex',
    category: 'Fitness',
    description: 'Home fitness equipment brand. Values home gym transformation stories and workout demonstrations.',
    tags: ['home-gym', 'resistance', 'equipment', 'transformation', 'strength'],
    budgetMin: 8000, budgetMax: 38000,
    compatibilityScore: 78, approvalRate: 65,
    difficulty: 'medium', campaignCount: 8,
    addedAt: '2026-03-30T00:00:00Z',
    requirements: ['Home gym setting required', 'Before/after space transformation valued', 'Real workout demonstrations with equipment'],
    bestFor: ['Home gym creators', 'Strength training accounts', 'Space transformation influencers'],
  },

  // ── TECH (18) ─────────────────────────────────────────────
  {
    id: 'apple',
    name: 'Apple',
    category: 'Tech',
    description: 'Most valuable brand in the world with elite creator standards. Extremely selective — creative concept must be pre-approved and align with Apple\'s visual language.',
    tags: ['premium', 'design', 'iphone', 'ecosystem', 'iconic'],
    budgetMin: 20000, budgetMax: 100000,
    compatibilityScore: 72, approvalRate: 38,
    difficulty: 'hard', campaignCount: 4,
    addedAt: '2026-05-10T00:00:00Z',
    requirements: ['Creative concept must be submitted and approved before filming', 'Apple aesthetic: clean, minimal, precise', 'No competitor products visible even in background', 'Professional production level expected'],
    bestFor: ['Tech creator influencers with Apple-first audiences', 'Creative and design-focused accounts', 'High-production photography and video creators'],
  },
  {
    id: 'samsung',
    name: 'Samsung',
    category: 'Tech',
    description: 'Global electronics brand with a more accessible creator program than Apple. Values real-world camera and feature demonstrations.',
    tags: ['android', 'camera', 'foldable', 'galaxy', 'consumer-tech'],
    budgetMin: 15000, budgetMax: 80000,
    compatibilityScore: 75, approvalRate: 52,
    difficulty: 'medium', campaignCount: 12,
    addedAt: '2026-01-16T00:00:00Z',
    requirements: ['Real-world feature demo required', 'Camera showcase content preferred', 'Android ecosystem creators preferred', 'No iPhone in the same video'],
    bestFor: ['Android tech creators', 'Mobile photography accounts', 'Gadget review influencers'],
  },
  {
    id: 'sony',
    name: 'Sony',
    category: 'Tech',
    description: 'Electronics and entertainment conglomerate. Values creators who bridge tech and creative pursuits — music, gaming, photography, film.',
    tags: ['audio', 'gaming', 'camera', 'entertainment', 'playstation'],
    budgetMin: 12000, budgetMax: 60000,
    compatibilityScore: 78, approvalRate: 60,
    difficulty: 'medium', campaignCount: 14,
    addedAt: '2026-02-02T00:00:00Z',
    requirements: ['Creative tech angle required — not just spec review', 'Show product in creative workflow', 'Gaming, music, or photography context preferred'],
    bestFor: ['Creative tech creators', 'Gaming and photography accounts', 'Music production influencers'],
  },
  {
    id: 'logitech',
    name: 'Logitech',
    category: 'Tech',
    description: 'Peripheral brand with the most creator-friendly program in tech. Extremely easy approval — authentic desk setup and gaming content is the brief.',
    tags: ['peripherals', 'gaming', 'mouse', 'keyboard', 'webcam'],
    budgetMin: 6000, budgetMax: 32000,
    compatibilityScore: 87, approvalRate: 80,
    difficulty: 'easy', campaignCount: 38,
    addedAt: '2025-12-18T00:00:00Z',
    requirements: ['Show product in real setup — no staged desk shots', 'Gaming or creator workspace context', 'Honest review including any negatives welcomed'],
    bestFor: ['Gaming creators', 'Creator workspace and setup accounts', 'WFH productivity influencers'],
  },
  {
    id: 'anker',
    name: 'Anker',
    category: 'Tech',
    description: 'Accessories and charging brand with the highest approval rate in tech. Volume creator program — easy entry for any tech-adjacent creator.',
    tags: ['charging', 'accessories', 'cables', 'powerbank', 'earbuds'],
    budgetMin: 4000, budgetMax: 20000,
    compatibilityScore: 90, approvalRate: 86,
    difficulty: 'easy', campaignCount: 45,
    addedAt: '2025-12-03T00:00:00Z',
    requirements: ['Show product solving a real problem in your life', 'Travel or on-the-go context scores well', 'Unboxing and honest first-use review format works'],
    bestFor: ['Tech accessory creators', 'Travel tech accounts', 'Any creator needing tech integration'],
  },
  {
    id: 'razer',
    name: 'Razer',
    category: 'Tech',
    description: 'Gaming hardware brand with strong creator culture. Easy approval for gaming creators — RGB and battle station content is the sweet spot.',
    tags: ['gaming', 'rgb', 'peripherals', 'esports', 'battle-station'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 85, approvalRate: 76,
    difficulty: 'easy', campaignCount: 26,
    addedAt: '2026-01-02T00:00:00Z',
    requirements: ['Gaming context required', 'Show product in actual gaming sessions', 'Esports or competitive gaming angle preferred'],
    bestFor: ['Gaming creators', 'Esports and competitive gaming accounts', 'Battle station setup influencers'],
  },
  {
    id: 'nothing',
    name: 'Nothing',
    category: 'Tech',
    description: 'Design-forward consumer tech startup. Extremely creator-friendly — built its brand on creator buzz. Values genuine enthusiasm and tech aesthetics.',
    tags: ['design', 'transparent', 'earbuds', 'phone', 'aesthetic'],
    budgetMin: 7000, budgetMax: 35000,
    compatibilityScore: 88, approvalRate: 82,
    difficulty: 'easy', campaignCount: 20,
    addedAt: '2026-04-08T00:00:00Z',
    requirements: ['Aesthetic and design appreciation required', 'Show the transparent design prominently', 'Genuine enthusiasm over scripted review'],
    bestFor: ['Tech aesthetic creators', 'Design-forward tech accounts', 'Minimalist tech lifestyle influencers'],
  },
  {
    id: 'oneplus',
    name: 'OnePlus',
    category: 'Tech',
    description: 'Community-driven Android smartphone brand. Easy approval for Android enthusiasts — values the "Never Settle" performance-first philosophy.',
    tags: ['android', 'flagship', 'speed', 'camera', 'value'],
    budgetMin: 8000, budgetMax: 38000,
    compatibilityScore: 86, approvalRate: 79,
    difficulty: 'easy', campaignCount: 18,
    addedAt: '2026-02-16T00:00:00Z',
    requirements: ['Android enthusiast community alignment required', 'Performance and speed demonstration preferred', 'Show camera capability in real scenarios'],
    bestFor: ['Android tech creators', 'Smartphone review accounts', 'Tech community influencers'],
  },
  {
    id: 'jbl',
    name: 'JBL',
    category: 'Tech',
    description: 'Audio brand with high-energy creator campaigns. Values content that shows speakers and headphones in social, lively environments.',
    tags: ['audio', 'speakers', 'bluetooth', 'music', 'outdoor'],
    budgetMin: 7000, budgetMax: 35000,
    compatibilityScore: 83, approvalRate: 74,
    difficulty: 'easy', campaignCount: 22,
    addedAt: '2026-01-28T00:00:00Z',
    requirements: ['Show product with music in social or outdoor setting', 'Energy and lifestyle integration required', 'Pool, beach, or party context scores highest'],
    bestFor: ['Lifestyle and music creators', 'Outdoor and adventure accounts', 'Social lifestyle influencers'],
  },
  {
    id: 'bose',
    name: 'Bose',
    category: 'Tech',
    description: 'Premium audio brand with medium difficulty. Values quiet confidence and genuine audio appreciation over hype.',
    tags: ['premium-audio', 'noise-cancelling', 'headphones', 'sound', 'focus'],
    budgetMin: 10000, budgetMax: 50000,
    compatibilityScore: 79, approvalRate: 62,
    difficulty: 'medium', campaignCount: 12,
    addedAt: '2026-03-04T00:00:00Z',
    requirements: ['Quiet confidence — no shouting or hype energy', 'Focus and concentration angle valued', 'Show product in genuine listening or work context'],
    bestFor: ['Productivity and focus creators', 'Music and audiophile accounts', 'Work and study lifestyle influencers'],
  },
  {
    id: 'rode',
    name: 'Rode',
    category: 'Tech',
    description: 'Professional audio equipment brand. Easy approval for video creators and podcasters — they want genuine production workflow integration.',
    tags: ['microphone', 'audio', 'podcast', 'filmmaking', 'professional'],
    budgetMin: 6000, budgetMax: 30000,
    compatibilityScore: 84, approvalRate: 76,
    difficulty: 'easy', campaignCount: 16,
    addedAt: '2026-02-24T00:00:00Z',
    requirements: ['Show product in real content creation workflow', 'Podcast, video, or film production context required', 'Honest audio quality comparison appreciated'],
    bestFor: ['Video and podcast creators', 'Filmmaking and production accounts', 'Audio engineering influencers'],
  },
  {
    id: 'google',
    name: 'Google',
    category: 'Tech',
    description: 'Tech giant with a focused Pixel and Workspace creator program. Hard difficulty — creative must align with Google\'s design-forward, helpful tech philosophy.',
    tags: ['pixel', 'android', 'workspace', 'ai', 'search'],
    budgetMin: 15000, budgetMax: 75000,
    compatibilityScore: 74, approvalRate: 48,
    difficulty: 'hard', campaignCount: 7,
    addedAt: '2026-04-30T00:00:00Z',
    requirements: ['Helpful technology angle required', 'Real-life problem being solved by product', 'No competitor devices (Apple, Samsung) in same video'],
    bestFor: ['Productivity tech creators', 'Android and Google ecosystem accounts', 'AI and tech innovation influencers'],
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    category: 'Tech',
    description: 'Software and devices brand with a broad creator program. Values productivity, creativity, and business efficiency storytelling.',
    tags: ['windows', 'xbox', 'surface', 'office', 'productivity'],
    budgetMin: 12000, budgetMax: 65000,
    compatibilityScore: 73, approvalRate: 50,
    difficulty: 'medium', campaignCount: 9,
    addedAt: '2026-05-05T00:00:00Z',
    requirements: ['Productivity or creativity workflow context required', 'Surface or Xbox campaigns have separate briefs', 'Enterprise storytelling valued for Workspace campaigns'],
    bestFor: ['Productivity and business creators', 'Gaming (Xbox) accounts', 'Creator workflow and setup influencers'],
  },
  {
    id: 'asus',
    name: 'Asus',
    category: 'Tech',
    description: 'Gaming and computing brand with easy creator access. Values honest hardware performance reviews and gaming content.',
    tags: ['gaming', 'laptop', 'rog', 'gpu', 'computing'],
    budgetMin: 7000, budgetMax: 35000,
    compatibilityScore: 82, approvalRate: 72,
    difficulty: 'easy', campaignCount: 20,
    addedAt: '2026-03-12T00:00:00Z',
    requirements: ['Gaming or performance computing context', 'Benchmark and real-use performance valued', 'ROG aesthetic works well in gaming setup content'],
    bestFor: ['Gaming creators', 'PC building and setup accounts', 'Mobile gaming influencers'],
  },
  {
    id: 'belkin',
    name: 'Belkin',
    category: 'Tech',
    description: 'Accessories brand with a high-volume creator program. Easy approval — values practical, problem-solving tech content.',
    tags: ['accessories', 'chargers', 'cases', 'cables', 'magsafe'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 84, approvalRate: 78,
    difficulty: 'easy', campaignCount: 30,
    addedAt: '2025-12-12T00:00:00Z',
    requirements: ['Show product solving a real daily problem', 'Apple ecosystem context preferred (MagSafe, etc.)', 'Desk setup or travel integration content works well'],
    bestFor: ['Apple ecosystem creators', 'Tech accessory accounts', 'Travel productivity influencers'],
  },
  {
    id: 'dell',
    name: 'Dell',
    category: 'Tech',
    description: 'Business and creator computing brand. Values workflow and productivity content over gaming — medium difficulty with solid budgets.',
    tags: ['laptop', 'monitor', 'business', 'creator', 'workstation'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 79, approvalRate: 65,
    difficulty: 'medium', campaignCount: 13,
    addedAt: '2026-02-20T00:00:00Z',
    requirements: ['Creative or professional workflow context required', 'Show product in real work environment', 'XPS or Alienware campaigns have separate briefs'],
    bestFor: ['Creator workflow accounts', 'Business and productivity influencers', 'Work-from-home lifestyle creators'],
  },
  {
    id: 'hp',
    name: 'HP',
    category: 'Tech',
    description: 'Computing and printing brand with a creator-accessible program. Values everyday productivity and creative use cases.',
    tags: ['laptop', 'printer', 'business', 'student', 'creativity'],
    budgetMin: 8000, budgetMax: 38000,
    compatibilityScore: 77, approvalRate: 62,
    difficulty: 'medium', campaignCount: 12,
    addedAt: '2026-03-18T00:00:00Z',
    requirements: ['Student, creative, or professional context', 'Spectre and Omen lines have premium creative briefs', 'Real productivity or creative workflow'],
    bestFor: ['Student lifestyle creators', 'Design and creative workflow accounts', 'Everyday productivity influencers'],
  },
  {
    id: 'lenovo',
    name: 'Lenovo',
    category: 'Tech',
    description: 'Global computing brand with accessible creator campaigns. Values professional and gaming content equally — ThinkPad and Legion are separate briefs.',
    tags: ['laptop', 'gaming', 'thinkpad', 'legion', 'business'],
    budgetMin: 8000, budgetMax: 38000,
    compatibilityScore: 80, approvalRate: 68,
    difficulty: 'medium', campaignCount: 15,
    addedAt: '2026-01-06T00:00:00Z',
    requirements: ['Professional or gaming context depending on product line', 'ThinkPad: business and reliability story', 'Legion: gaming performance and setup content'],
    bestFor: ['Business and gaming creators', 'Work productivity accounts', 'Gaming setup influencers'],
  },

  // ── FOOD (16) ─────────────────────────────────────────────
  {
    id: 'red-bull',
    name: 'Red Bull',
    category: 'Food',
    description: 'The original energy drink brand. Values extreme sport, music, and creative culture content — not nutrition or health content. High energy is the requirement.',
    tags: ['energy', 'extreme-sport', 'music', 'culture', 'event'],
    budgetMin: 8000, budgetMax: 45000,
    compatibilityScore: 83, approvalRate: 72,
    difficulty: 'easy', campaignCount: 28,
    addedAt: '2025-12-08T00:00:00Z',
    requirements: ['High-energy sport or culture context required', 'Do NOT use health or nutrition angle — brand forbids it', 'Creator energy must match brand intensity'],
    bestFor: ['Extreme sport creators', 'Music and culture accounts', 'High-energy lifestyle influencers'],
  },
  {
    id: 'ag1',
    name: 'AG1 (Athletic Greens)',
    category: 'Food',
    description: 'Premium all-in-one nutrition brand with the highest brand-creator alignment in supplements. Authentic morning ritual content is the brief.',
    tags: ['greens', 'nutrition', 'morning-routine', 'wellness', 'premium'],
    budgetMin: 6000, budgetMax: 35000,
    compatibilityScore: 89, approvalRate: 82,
    difficulty: 'easy', campaignCount: 30,
    addedAt: '2025-12-15T00:00:00Z',
    requirements: ['Morning routine integration — not mid-day or post-workout', 'Show genuine daily habit', 'Health optimization lifestyle alignment required', 'No meal replacement positioning'],
    bestFor: ['Health optimization creators', 'Morning routine accounts', 'Biohacking and wellness influencers'],
  },
  {
    id: 'huel',
    name: 'Huel',
    category: 'Food',
    description: 'Complete nutrition brand that rewards honest, practical content. Creators who integrate Huel into real busy schedules get highest approval.',
    tags: ['meal-replacement', 'nutrition', 'complete-food', 'busy', 'practical'],
    budgetMin: 5000, budgetMax: 28000,
    compatibilityScore: 85, approvalRate: 78,
    difficulty: 'easy', campaignCount: 22,
    addedAt: '2026-01-14T00:00:00Z',
    requirements: ['Busy lifestyle integration angle required', 'Honest review of taste and convenience', 'No fitness-only positioning — brand is for everyone'],
    bestFor: ['Busy professional creators', 'Nutrition and meal prep accounts', 'Practical wellness influencers'],
  },
  {
    id: 'oatly',
    name: 'Oatly',
    category: 'Food',
    description: 'Provocative oat milk brand with a distinct brand personality. Values creators who match their irreverent, sustainability-conscious tone.',
    tags: ['oat-milk', 'sustainability', 'dairy-free', 'provocative', 'barista'],
    budgetMin: 5000, budgetMax: 25000,
    compatibilityScore: 82, approvalRate: 73,
    difficulty: 'easy', campaignCount: 16,
    addedAt: '2026-02-08T00:00:00Z',
    requirements: ['Sustainability or dairy-free angle', 'Oatly tone: self-aware and slightly irreverent', 'Coffee or cooking integration preferred', 'No nutritional claims'],
    bestFor: ['Sustainability creators', 'Coffee and cafe culture accounts', 'Plant-based lifestyle influencers'],
  },
  {
    id: 'monster-energy',
    name: 'Monster Energy',
    category: 'Food',
    description: 'Energy drink brand with a motorsport, gaming, and extreme sport focus. Accessible to gaming and action sport creators.',
    tags: ['energy', 'gaming', 'motorsport', 'extreme', 'esports'],
    budgetMin: 7000, budgetMax: 38000,
    compatibilityScore: 80, approvalRate: 68,
    difficulty: 'medium', campaignCount: 20,
    addedAt: '2026-01-22T00:00:00Z',
    requirements: ['Gaming, motorsport, or extreme sport context', 'High energy aesthetic required', 'Creator must be in target 18-30 demographic or speak to it'],
    bestFor: ['Gaming creators', 'Motorsport accounts', 'Extreme sport influencers'],
  },
  {
    id: 'rxbar',
    name: 'RXBAR',
    category: 'Food',
    description: 'No-BS protein bar brand. Values transparent, no-filter content that matches their "No B.S." ingredient philosophy.',
    tags: ['protein-bar', 'clean', 'no-bs', 'fitness', 'paleo'],
    budgetMin: 4000, budgetMax: 20000,
    compatibilityScore: 84, approvalRate: 78,
    difficulty: 'easy', campaignCount: 18,
    addedAt: '2026-03-06T00:00:00Z',
    requirements: ['Honest, straightforward content — no hype', 'Show product in genuine active lifestyle context', 'Ingredient transparency angle valued'],
    bestFor: ['Fitness and active lifestyle creators', 'Clean eating accounts', 'CrossFit and functional fitness influencers'],
  },
  {
    id: 'kind-snacks',
    name: 'Kind Snacks',
    category: 'Food',
    description: 'Nut bar brand with a kindness philosophy. Easy approval for lifestyle and wellness creators — values positive, uplifting content.',
    tags: ['snack', 'nuts', 'healthy', 'kindness', 'on-the-go'],
    budgetMin: 4000, budgetMax: 18000,
    compatibilityScore: 83, approvalRate: 76,
    difficulty: 'easy', campaignCount: 20,
    addedAt: '2026-02-26T00:00:00Z',
    requirements: ['Positive lifestyle or on-the-go context', 'Kindness and community angle valued', 'Show product as natural part of active day'],
    bestFor: ['Wellness lifestyle creators', 'Outdoor and active accounts', 'Positive mindset influencers'],
  },
  {
    id: 'magic-spoon',
    name: 'Magic Spoon',
    category: 'Food',
    description: 'Better-for-you cereal brand with a massive creator program. Easy approval — built on creator partnerships and nostalgia-meets-nutrition storytelling.',
    tags: ['cereal', 'protein', 'healthy', 'nostalgic', 'keto'],
    budgetMin: 5000, budgetMax: 25000,
    compatibilityScore: 87, approvalRate: 80,
    difficulty: 'easy', campaignCount: 28,
    addedAt: '2025-12-18T00:00:00Z',
    requirements: ['Nostalgia angle — "childhood cereal but better" framing preferred', 'Morning routine integration', 'Honest flavor review is welcomed'],
    bestFor: ['Health food creators', 'Morning routine accounts', 'Keto and macro-tracking influencers'],
  },
  {
    id: 'clif-bar',
    name: 'Clif Bar',
    category: 'Food',
    description: 'Outdoor and adventure nutrition brand. Values genuine outdoor activity content — climbing, cycling, hiking.',
    tags: ['energy-bar', 'outdoor', 'adventure', 'cycling', 'climbing'],
    budgetMin: 4000, budgetMax: 18000,
    compatibilityScore: 81, approvalRate: 73,
    difficulty: 'easy', campaignCount: 15,
    addedAt: '2026-02-14T00:00:00Z',
    requirements: ['Outdoor adventure context required', 'Show product as on-the-go fuel — not gym supplement', 'Sustainability and environmental angle valued'],
    bestFor: ['Outdoor and adventure creators', 'Cycling and climbing accounts', 'Active lifestyle influencers'],
  },
  {
    id: 'innocent',
    name: 'Innocent',
    category: 'Food',
    description: 'British smoothie brand with a playful, ethical personality. Easy approval for lifestyle creators — values fun, fresh, and sustainability-forward content.',
    tags: ['smoothie', 'british', 'ethical', 'playful', 'fruit'],
    budgetMin: 4000, budgetMax: 20000,
    compatibilityScore: 80, approvalRate: 72,
    difficulty: 'easy', campaignCount: 14,
    addedAt: '2026-03-18T00:00:00Z',
    requirements: ['Fun, lighthearted tone required — brand is famously playful', 'Sustainability or ethical living angle appreciated', 'Show in everyday, happy lifestyle moment'],
    bestFor: ['Lifestyle and wellness creators', 'UK-based content accounts', 'Sustainability and ethical living influencers'],
  },
  {
    id: 'chobani',
    name: 'Chobani',
    category: 'Food',
    description: 'Greek yogurt brand with a community and wellness focus. Easy approval for everyday healthy lifestyle creators.',
    tags: ['yogurt', 'protein', 'breakfast', 'wellness', 'community'],
    budgetMin: 4000, budgetMax: 18000,
    compatibilityScore: 79, approvalRate: 70,
    difficulty: 'easy', campaignCount: 16,
    addedAt: '2026-01-30T00:00:00Z',
    requirements: ['Morning or breakfast routine integration', 'Healthy lifestyle or fitness adjacent context', 'Family or community angle valued'],
    bestFor: ['Healthy lifestyle creators', 'Breakfast and morning routine accounts', 'Family and wellness influencers'],
  },
  {
    id: 'daily-harvest',
    name: 'Daily Harvest',
    category: 'Food',
    description: 'Frozen smoothie and food delivery brand. Values time-saving healthy lifestyle content — busy professionals are the ideal creator persona.',
    tags: ['smoothie', 'frozen', 'delivery', 'healthy', 'convenient'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 82, approvalRate: 74,
    difficulty: 'easy', campaignCount: 14,
    addedAt: '2026-04-12T00:00:00Z',
    requirements: ['Busy lifestyle angle — show time-saving value', 'Morning routine or meal prep context', 'Aesthetic unboxing appreciated'],
    bestFor: ['Busy professional creators', 'Healthy meal prep accounts', 'Wellness convenience influencers'],
  },
  {
    id: 'soylent',
    name: 'Soylent',
    category: 'Food',
    description: 'Complete nutrition drink for productivity-focused individuals. Medium difficulty — values tech worker, gamer, and high-performer audience alignment.',
    tags: ['meal-replacement', 'nutrition', 'productivity', 'tech', 'complete'],
    budgetMin: 4000, budgetMax: 20000,
    compatibilityScore: 78, approvalRate: 68,
    difficulty: 'medium', campaignCount: 10,
    addedAt: '2026-04-22T00:00:00Z',
    requirements: ['Productivity or tech lifestyle context', 'Show product as fuel for deep work or gaming sessions', 'No fitness-only positioning'],
    bestFor: ['Tech and productivity creators', 'Gaming and esports accounts', 'Deep work lifestyle influencers'],
  },
  {
    id: 'butcher-box',
    name: 'ButcherBox',
    category: 'Food',
    description: 'Premium meat delivery subscription. Values cooking content and values-driven food sourcing stories.',
    tags: ['meat', 'subscription', 'cooking', 'grass-fed', 'premium'],
    budgetMin: 6000, budgetMax: 28000,
    compatibilityScore: 80, approvalRate: 72,
    difficulty: 'easy', campaignCount: 14,
    addedAt: '2026-03-24T00:00:00Z',
    requirements: ['Cooking content with product — not just unboxing', 'Values-driven food sourcing angle valued', 'Show preparation and meal result'],
    bestFor: ['Cooking and food creators', 'Carnivore and paleo diet accounts', 'Values-driven lifestyle influencers'],
  },
  {
    id: 'green-chef',
    name: 'Green Chef',
    category: 'Food',
    description: 'USDA-certified organic meal kit service. Values sustainability and cooking skill development content.',
    tags: ['meal-kit', 'organic', 'cooking', 'sustainability', 'family'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 78, approvalRate: 68,
    difficulty: 'medium', campaignCount: 12,
    addedAt: '2026-02-28T00:00:00Z',
    requirements: ['Show full cooking process — not just final meal', 'Organic and sustainability angle required', 'Family or couple cooking context preferred'],
    bestFor: ['Family and couple lifestyle creators', 'Sustainability food accounts', 'Home cooking and meal prep influencers'],
  },
  {
    id: 'factor',
    name: 'Factor',
    category: 'Food',
    description: 'Prepared meal delivery service for fitness-focused individuals. Easy approval for health and fitness lifestyle creators.',
    tags: ['prepared-meals', 'delivery', 'macro-friendly', 'fitness', 'convenient'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 79, approvalRate: 70,
    difficulty: 'easy', campaignCount: 16,
    addedAt: '2026-04-02T00:00:00Z',
    requirements: ['Fitness lifestyle or busy professional context', 'Show macro tracking angle where relevant', 'Unboxing + eating the meal format performs best'],
    bestFor: ['Fitness lifestyle creators', 'Macro-tracking and diet accounts', 'Busy professional wellness influencers'],
  },

  // ── TRAVEL (16) ───────────────────────────────────────────
  {
    id: 'airbnb',
    name: 'Airbnb',
    category: 'Travel',
    description: 'Short-term rental platform that values authentic experience storytelling. Medium difficulty — creator must demonstrate genuine travel personality.',
    tags: ['accommodation', 'experience', 'community', 'travel', 'unique-stays'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 80, approvalRate: 65,
    difficulty: 'medium', campaignCount: 15,
    addedAt: '2026-01-20T00:00:00Z',
    requirements: ['Show the experience — not just the property', 'Community and local culture angle valued', 'Unique stays (treehouses, cabins) outperform standard apartments'],
    bestFor: ['Travel experience creators', 'Lifestyle adventure accounts', 'Community and local culture influencers'],
  },
  {
    id: 'booking-com',
    name: 'Booking.com',
    category: 'Travel',
    description: 'Online travel booking platform with a broad creator program. Values practical travel planning content over aspirational luxury.',
    tags: ['booking', 'hotels', 'practical', 'savings', 'travel-planning'],
    budgetMin: 7000, budgetMax: 35000,
    compatibilityScore: 78, approvalRate: 62,
    difficulty: 'medium', campaignCount: 18,
    addedAt: '2026-02-10T00:00:00Z',
    requirements: ['Practical travel planning angle preferred', 'Show app interface in real booking scenario', 'Budget-conscious travel tips content works well'],
    bestFor: ['Budget travel creators', 'Travel planning and tips accounts', 'Digital nomad influencers'],
  },
  {
    id: 'peak-design',
    name: 'Peak Design',
    category: 'Travel',
    description: 'Premium travel and camera gear brand built on Kickstarter community. Extremely easy approval for photographer and travel creator community.',
    tags: ['camera-gear', 'bags', 'travel', 'photography', 'modular'],
    budgetMin: 5000, budgetMax: 28000,
    compatibilityScore: 88, approvalRate: 82,
    difficulty: 'easy', campaignCount: 20,
    addedAt: '2026-01-08T00:00:00Z',
    requirements: ['Photography or videography travel context required', 'Show gear in real travel or adventure use', 'Community feel — creator should be a genuine fan'],
    bestFor: ['Travel photographer creators', 'Camera gear review accounts', 'Adventure filmmaking influencers'],
  },
  {
    id: 'away-luggage',
    name: 'Away',
    category: 'Travel',
    description: 'Modern direct-to-consumer luggage brand. Easy approval for aspirational travel creators — content integrates naturally with travel lifestyle.',
    tags: ['luggage', 'travel', 'minimalist', 'premium-dtr', 'carry-on'],
    budgetMin: 6000, budgetMax: 28000,
    compatibilityScore: 82, approvalRate: 74,
    difficulty: 'easy', campaignCount: 16,
    addedAt: '2026-02-18T00:00:00Z',
    requirements: ['Real travel context — must show product being used on a trip', 'Minimalist packing and travel efficiency angle', 'Aspirational but accessible destinations'],
    bestFor: ['Travel lifestyle creators', 'Minimalist packing accounts', 'Business and leisure travel influencers'],
  },
  {
    id: 'osprey',
    name: 'Osprey',
    category: 'Travel',
    description: 'Premium outdoor pack brand with genuine adventure creator community. Easy for outdoor and hiking creators — authenticity over aesthetics.',
    tags: ['backpack', 'hiking', 'outdoor', 'adventure', 'trekking'],
    budgetMin: 4000, budgetMax: 20000,
    compatibilityScore: 84, approvalRate: 78,
    difficulty: 'easy', campaignCount: 18,
    addedAt: '2025-12-22T00:00:00Z',
    requirements: ['Genuine outdoor adventure context required', 'Show pack loaded and in use on trail', 'Technical features and fit discussion valued'],
    bestFor: ['Hiking and trekking creators', 'Outdoor adventure accounts', 'Backpacking and expedition influencers'],
  },
  {
    id: 'samsonite',
    name: 'Samsonite',
    category: 'Travel',
    description: 'Heritage luggage brand with medium difficulty. Values business travel and premium experience content over backpacker positioning.',
    tags: ['luggage', 'business-travel', 'premium', 'heritage', 'durable'],
    budgetMin: 7000, budgetMax: 35000,
    compatibilityScore: 79, approvalRate: 65,
    difficulty: 'medium', campaignCount: 12,
    addedAt: '2026-03-14T00:00:00Z',
    requirements: ['Business or premium travel context', 'Show product in airports and hotels — not backpacker hostels', 'Durability and quality storytelling valued'],
    bestFor: ['Business travel creators', 'Premium lifestyle travel accounts', 'Frequent flyer influencers'],
  },
  {
    id: 'emirates',
    name: 'Emirates',
    category: 'Travel',
    description: 'Premium airline with high creator standards. Hard difficulty — requires access to premium or business class and luxury travel aesthetic.',
    tags: ['airline', 'luxury', 'business-class', 'long-haul', 'premium'],
    budgetMin: 15000, budgetMax: 70000,
    compatibilityScore: 72, approvalRate: 48,
    difficulty: 'hard', campaignCount: 5,
    addedAt: '2026-05-02T00:00:00Z',
    requirements: ['Premium or business class travel context expected', 'Luxury destination and lifestyle required', 'Cinematic production quality expected'],
    bestFor: ['Luxury travel creators', 'Business class and premium travel accounts', 'High-net-worth lifestyle influencers'],
  },
  {
    id: 'qatar-airways',
    name: 'Qatar Airways',
    category: 'Travel',
    description: 'World-class airline with selective creator partnerships. Hard difficulty — values prestige, excellence, and premium travel storytelling.',
    tags: ['airline', 'luxury', 'premium', 'global', 'qatar'],
    budgetMin: 15000, budgetMax: 65000,
    compatibilityScore: 70, approvalRate: 45,
    difficulty: 'hard', campaignCount: 4,
    addedAt: '2026-05-12T00:00:00Z',
    requirements: ['Prestige and excellence positioning required', 'Luxury travel lifestyle alignment', 'No budget travel messaging or audience overlap'],
    bestFor: ['Luxury travel creators', 'Global travel and lifestyle accounts', 'Premium business travel influencers'],
  },
  {
    id: 'indigo',
    name: 'IndiGo',
    category: 'Travel',
    description: 'India\'s largest airline with a value-focused creator program. Easy entry for India-based lifestyle and travel creators.',
    tags: ['indian-airline', 'domestic', 'affordable', 'punctual', 'india'],
    budgetMin: 5000, budgetMax: 25000,
    compatibilityScore: 76, approvalRate: 62,
    difficulty: 'medium', campaignCount: 16,
    addedAt: '2026-02-04T00:00:00Z',
    requirements: ['India-based travel context', 'Value for money travel angle', 'Domestic destination discovery content valued'],
    bestFor: ['Indian travel creators', 'Domestic travel accounts', 'Budget and value travel influencers'],
  },
  {
    id: 'makemytrip',
    name: 'MakeMyTrip',
    category: 'Travel',
    description: 'India\'s leading travel platform. Easy approval for India-based creators — values destination discovery and booking journey content.',
    tags: ['india', 'booking', 'domestic', 'holidays', 'travel-planning'],
    budgetMin: 5000, budgetMax: 22000,
    compatibilityScore: 79, approvalRate: 68,
    difficulty: 'medium', campaignCount: 20,
    addedAt: '2026-01-26T00:00:00Z',
    requirements: ['India-centric travel content required', 'Show trip planning and booking journey', 'Hidden gem and underrated destination angle preferred'],
    bestFor: ['Indian travel creators', 'Domestic holiday accounts', 'Budget travel and deal-finding influencers'],
  },
  {
    id: 'tripadvisor',
    name: 'Tripadvisor',
    category: 'Travel',
    description: 'Travel review platform with a creator review program. Values honest, experience-based content — restaurant, hotel, and attraction reviews.',
    tags: ['reviews', 'hotels', 'restaurants', 'experiences', 'travel-tips'],
    budgetMin: 4000, budgetMax: 18000,
    compatibilityScore: 74, approvalRate: 60,
    difficulty: 'medium', campaignCount: 14,
    addedAt: '2026-03-22T00:00:00Z',
    requirements: ['Honest experience review required — not promotional tone', 'Show review discovery and booking process', 'Restaurant or attraction review format works well'],
    bestFor: ['Travel review creators', 'Food and restaurant accounts', 'Honest destination guide influencers'],
  },
  {
    id: 'marriott',
    name: 'Marriott',
    category: 'Travel',
    description: 'Global hotel group with a premium creator program. Medium difficulty — values aspirational hotel experience and loyalty program storytelling.',
    tags: ['hotels', 'luxury', 'business', 'loyalty', 'global'],
    budgetMin: 8000, budgetMax: 40000,
    compatibilityScore: 76, approvalRate: 55,
    difficulty: 'medium', campaignCount: 8,
    addedAt: '2026-04-06T00:00:00Z',
    requirements: ['Premium hotel experience context', 'Loyalty program integration valued', 'Show amenities and experience — not just the room'],
    bestFor: ['Premium travel creators', 'Business and luxury travel accounts', 'Hotel experience influencers'],
  },
  {
    id: 'hilton',
    name: 'Hilton',
    category: 'Travel',
    description: 'Global hotel group with a strong Honors loyalty creator program. Hard difficulty — values prestige and aspirational travel lifestyle.',
    tags: ['hotels', 'luxury', 'hilton-honors', 'global', 'aspirational'],
    budgetMin: 8000, budgetMax: 38000,
    compatibilityScore: 74, approvalRate: 52,
    difficulty: 'hard', campaignCount: 7,
    addedAt: '2026-04-14T00:00:00Z',
    requirements: ['Aspirational travel and luxury lifestyle required', 'Hilton Honors loyalty angle preferred', 'Cinematic property showcase content'],
    bestFor: ['Luxury travel creators', 'Aspirational lifestyle accounts', 'Frequent hotel traveler influencers'],
  },
  {
    id: 'accor',
    name: 'Accor Hotels',
    category: 'Travel',
    description: 'European hotel group with diverse brand portfolio (Novotel, Sofitel, Ibis). Values varied travel contexts across budget to luxury segments.',
    tags: ['hotels', 'european', 'luxury', 'business', 'boutique'],
    budgetMin: 7000, budgetMax: 32000,
    compatibilityScore: 73, approvalRate: 55,
    difficulty: 'medium', campaignCount: 10,
    addedAt: '2026-03-26T00:00:00Z',
    requirements: ['Match creator aesthetic to specific brand tier (Ibis vs Sofitel)', 'European travel context preferred', 'Show authentic hotel stay experience'],
    bestFor: ['European travel creators', 'Business and leisure travel accounts', 'Hotel lifestyle influencers'],
  },
  {
    id: 'radisson',
    name: 'Radisson',
    category: 'Travel',
    description: 'International hotel group with a business travel focus. Medium difficulty with consistent campaign availability.',
    tags: ['hotels', 'business', 'conference', 'international', 'rewards'],
    budgetMin: 6000, budgetMax: 28000,
    compatibilityScore: 75, approvalRate: 60,
    difficulty: 'medium', campaignCount: 9,
    addedAt: '2026-02-22T00:00:00Z',
    requirements: ['Business travel lifestyle or conference context preferred', 'Rewards program integration valued', 'Professional setting — not leisure backpacker content'],
    bestFor: ['Business travel creators', 'Corporate lifestyle accounts', 'Conference and event travel influencers'],
  },
  {
    id: 'expedia',
    name: 'Expedia',
    category: 'Travel',
    description: 'Online travel platform with a broad creator program. Values deal-finding, itinerary planning, and trip inspiration content.',
    tags: ['booking', 'flights', 'hotels', 'packages', 'deals'],
    budgetMin: 7000, budgetMax: 32000,
    compatibilityScore: 75, approvalRate: 58,
    difficulty: 'medium', campaignCount: 14,
    addedAt: '2026-03-02T00:00:00Z',
    requirements: ['Trip planning and discovery angle preferred', 'Show booking process naturally', 'Budget-to-luxury range all accepted'],
    bestFor: ['Trip planning creators', 'Travel deal accounts', 'Family and couples travel influencers'],
  },
]

// ── Saved brands (localStorage) ───────────────────────────────

const SAVED_KEY = 'intent_saved_brands'

export function getSavedBrandIds(): Set<string> {
  try {
    const raw = localStorage.getItem(SAVED_KEY)
    return new Set(raw ? (JSON.parse(raw) as string[]) : [])
  } catch {
    return new Set()
  }
}

function persistSaved(ids: Set<string>): void {
  localStorage.setItem(SAVED_KEY, JSON.stringify([...ids]))
}

export function toggleSaveBrand(id: string, current: Set<string>): Set<string> {
  const next = new Set(current)
  if (next.has(id)) next.delete(id)
  else next.add(id)
  persistSaved(next)
  window.dispatchEvent(new CustomEvent('intent:store-updated', { detail: 'brands' }))
  return next
}

// ── Query ─────────────────────────────────────────────────────

export function searchBrands(
  query: string,
  category: FilterCategory,
  sort: SortOption,
): DiscoveryBrand[] {
  let results = [...BRANDS]

  if (category !== 'all') {
    results = results.filter((b) => b.category === category)
  }

  if (query.trim()) {
    const q = query.toLowerCase()
    results = results.filter(
      (b) =>
        b.name.toLowerCase().includes(q) ||
        b.category.toLowerCase().includes(q) ||
        b.description.toLowerCase().includes(q) ||
        b.tags.some((t) => t.includes(q)),
    )
  }

  switch (sort) {
    case 'match':
      return results.sort((a, b) => b.compatibilityScore - a.compatibilityScore)
    case 'budget':
      return results.sort((a, b) => b.budgetMax - a.budgetMax)
    case 'approval':
      return results.sort((a, b) => b.approvalRate - a.approvalRate)
    case 'newest':
      return results.sort(
        (a, b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime(),
      )
  }
}

export function getTotalCount(): number {
  return BRANDS.length
}

// ── Display helpers ───────────────────────────────────────────

export function formatBudget(min: number, max: number): string {
  const fmt = (n: number) => (n >= 1000 ? `$${(n / 1000).toFixed(0)}K` : `$${n}`)
  return `${fmt(min)} – ${fmt(max)}`
}

export function scoreColor(s: number): string {
  if (s >= 85) return '#F5A653'
  if (s >= 70) return '#EAB308'
  return '#6B7280'
}

export function scoreLabel(s: number): string {
  if (s >= 85) return 'Excellent'
  if (s >= 75) return 'Strong'
  if (s >= 65) return 'Good'
  return 'Fair'
}
